//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity.VisualScripting.Generated.PropertyProviders
{
	
	
	[global::Unity.VisualScripting.SerializedPropertyProviderAttribute(typeof(global::Unity.VisualScripting.Community.Libraries.CSharp.SystemType))]
	public class PropertyProvider_Unity_VisualScripting_Community_Libraries_CSharp_SystemType : Unity.VisualScripting.SerializedPropertyProvider<Unity.VisualScripting.Community.Libraries.CSharp.SystemType>
	{
	}
}
