//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity.VisualScripting.Generated.PropertyProviders
{
	
	
	[global::Unity.VisualScripting.SerializedPropertyProviderAttribute(typeof(global::UnityEngine.AddressableAssets.AssetReferenceTexture2D))]
	public class PropertyProvider_UnityEngine_AddressableAssets_AssetReferenceTexture2D : Unity.VisualScripting.SerializedPropertyProvider<UnityEngine.AddressableAssets.AssetReferenceTexture2D>
	{
	}
}
